@url = http://localhost:8080

GET {{url}}/filmes

###
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Star Trek: The Motion Picture",
    "idGenero" : 2,
    "idsProdutoras": [2,3]
}

###
PUT {{url}}/filmes/1
Content-Type: application/json

{
    "titulo" :  "A Sociedade do Anel",
    "idGenero" : 1,
    "idsProdutoras" : [2]
}

###
GET {{url}}/filmes/1

###
DELETE {{url}}/filmes/2